### ISSUE TITLE
Region 2

### ISSUE THREAD

**Issue by Frikkie50** [ThePheonixGuy/sunsynk-scraper-addon#22]
Howdy

Me again. How easy would it be to hook this up to region 2?

**Comment by chris2172** [comment]
I got it working for region 2 by updating endpoints.py. Have not done full testing but it logged into sunsynk and pushed some data to MQTT

#login_endpoint = ('https://pv.inteless.com/oauth/token')
#plants_endpoint = ('https://pv.inteless.com/api/v1/plants?page=1&limit=10&name=&status=')
#energy_base_url = "https://pv.inteless.com/api/v1/plant/energy/"

login_endpoint = ('https://api.sunsynk.net/oauth/token')
plants_endpoint = ('https://api.sunsynk.net/api/v1/plants?page=1&limit=10&name=&status=')                  
energy_base_url = "https://api.sunsynk.net/api/v1/plant/energy/"
inverter_list_url = "https://api.sunsynk.net/api/v1/inverters?page=1&limit=10&status=-1&type=-1"

**Comment by ThePheonixGuy** [comment]
Hello! 

Yeah, just needs a minor update to the api urls. @chris2172 If you wanna open a PR for that, I'd be quite happy to merge it in!

**Comment by chris2172** [comment]
If there are no more users in Region 1 it is simple to replace the URLs
But if there are still users in Region 1 then it would be best to add a Region selector in the config
@ThePheonixGuy

**Comment by krazysh01** [comment]
resolved in https://github.com/ThePheonixGuy/sunsynk-scraper-addon/pull/24
